const QUERYKEY_USER = 'user';
const QUERYKEY_CONFERENCES = 'conferences';
const QUERYKEY_CONFERENCE = 'conference';
const QUERYKEY_AGENDA = 'agenda';

export {
  QUERYKEY_USER,
  QUERYKEY_CONFERENCES,
  QUERYKEY_CONFERENCE,
  QUERYKEY_AGENDA,
};
