FROM node:latest as builder

WORKDIR /app

COPY package.json ./

COPY yarn.lock ./

RUN yarn install --ignore-engines

RUN rm -rf ./.next/cachek

COPY . .

ENV NODE_ENV dev

RUN yarn build

EXPOSE 3000

CMD ["yarn", "dev"]