FROM node:18-alpine

WORKDIR /app

COPY package.json ./

COPY yarn.lock ./

RUN yarn install --ignore-scripts

RUN rm -rf ./.next/cachek

COPY . .

ENV NODE_ENV dev

RUN yarn build

RUN yarn build

CMD ["yarn", "dev"]